// third_party/blink/public/mojom/otter/otter_broker.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'third_party/blink/public/mojom/otter/otter_broker.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('blink.mojom');



  function OtterBrokerService_Init_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  OtterBrokerService_Init_Params.prototype.initDefaults_ = function() {
    this.host = null;
  };
  OtterBrokerService_Init_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  OtterBrokerService_Init_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate OtterBrokerService_Init_Params.host
    err = messageValidator.validateStringPointer(offset + codec.kStructHeaderSize + 0, false)
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  OtterBrokerService_Init_Params.encodedSize = codec.kStructHeaderSize + 8;

  OtterBrokerService_Init_Params.decode = function(decoder) {
    var packed;
    var val = new OtterBrokerService_Init_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.host =
        decoder.decodeStruct(codec.String);
    return val;
  };

  OtterBrokerService_Init_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(OtterBrokerService_Init_Params.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.String, val.host);
  };
  function OtterBrokerService_Init_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  OtterBrokerService_Init_ResponseParams.prototype.initDefaults_ = function() {
  };
  OtterBrokerService_Init_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  OtterBrokerService_Init_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  OtterBrokerService_Init_ResponseParams.encodedSize = codec.kStructHeaderSize + 0;

  OtterBrokerService_Init_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new OtterBrokerService_Init_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  OtterBrokerService_Init_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(OtterBrokerService_Init_ResponseParams.encodedSize);
    encoder.writeUint32(0);
  };
  function OtterBrokerService_GetSlot_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  OtterBrokerService_GetSlot_Params.prototype.initDefaults_ = function() {
  };
  OtterBrokerService_GetSlot_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  OtterBrokerService_GetSlot_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 8}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  OtterBrokerService_GetSlot_Params.encodedSize = codec.kStructHeaderSize + 0;

  OtterBrokerService_GetSlot_Params.decode = function(decoder) {
    var packed;
    var val = new OtterBrokerService_GetSlot_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    return val;
  };

  OtterBrokerService_GetSlot_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(OtterBrokerService_GetSlot_Params.encodedSize);
    encoder.writeUint32(0);
  };
  function OtterBrokerService_GetSlot_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  OtterBrokerService_GetSlot_ResponseParams.prototype.initDefaults_ = function() {
    this.slot = 0;
  };
  OtterBrokerService_GetSlot_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  OtterBrokerService_GetSlot_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  OtterBrokerService_GetSlot_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  OtterBrokerService_GetSlot_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new OtterBrokerService_GetSlot_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.slot =
        decoder.decodeStruct(codec.Uint64);
    return val;
  };

  OtterBrokerService_GetSlot_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(OtterBrokerService_GetSlot_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStruct(codec.Uint64, val.slot);
  };
  var kOtterBrokerService_Init_Name = 0;
  var kOtterBrokerService_GetSlot_Name = 1;

  function OtterBrokerServicePtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(OtterBrokerService,
                                                   handleOrPtrInfo);
  }

  function OtterBrokerServiceAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        OtterBrokerService, associatedInterfacePtrInfo);
  }

  OtterBrokerServiceAssociatedPtr.prototype =
      Object.create(OtterBrokerServicePtr.prototype);
  OtterBrokerServiceAssociatedPtr.prototype.constructor =
      OtterBrokerServiceAssociatedPtr;

  function OtterBrokerServiceProxy(receiver) {
    this.receiver_ = receiver;
  }
  OtterBrokerServicePtr.prototype.init = function() {
    return OtterBrokerServiceProxy.prototype.init
        .apply(this.ptr.getProxy(), arguments);
  };

  OtterBrokerServiceProxy.prototype.init = function(host) {
    var params_ = new OtterBrokerService_Init_Params();
    params_.host = host;
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kOtterBrokerService_Init_Name,
          codec.align(OtterBrokerService_Init_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(OtterBrokerService_Init_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(OtterBrokerService_Init_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };
  OtterBrokerServicePtr.prototype.getSlot = function() {
    return OtterBrokerServiceProxy.prototype.getSlot
        .apply(this.ptr.getProxy(), arguments);
  };

  OtterBrokerServiceProxy.prototype.getSlot = function() {
    var params_ = new OtterBrokerService_GetSlot_Params();
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kOtterBrokerService_GetSlot_Name,
          codec.align(OtterBrokerService_GetSlot_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(OtterBrokerService_GetSlot_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(OtterBrokerService_GetSlot_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function OtterBrokerServiceStub(delegate) {
    this.delegate_ = delegate;
  }
  OtterBrokerServiceStub.prototype.init = function(host) {
    return this.delegate_ && this.delegate_.init && this.delegate_.init(host);
  }
  OtterBrokerServiceStub.prototype.getSlot = function() {
    return this.delegate_ && this.delegate_.getSlot && this.delegate_.getSlot();
  }

  OtterBrokerServiceStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  OtterBrokerServiceStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kOtterBrokerService_Init_Name:
      var params = reader.decodeStruct(OtterBrokerService_Init_Params);
      this.init(params.host).then(function(response) {
        var responseParams =
            new OtterBrokerService_Init_ResponseParams();
        var builder = new codec.MessageV1Builder(
            kOtterBrokerService_Init_Name,
            codec.align(OtterBrokerService_Init_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(OtterBrokerService_Init_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    case kOtterBrokerService_GetSlot_Name:
      var params = reader.decodeStruct(OtterBrokerService_GetSlot_Params);
      this.getSlot().then(function(response) {
        var responseParams =
            new OtterBrokerService_GetSlot_ResponseParams();
        responseParams.slot = response.slot;
        var builder = new codec.MessageV1Builder(
            kOtterBrokerService_GetSlot_Name,
            codec.align(OtterBrokerService_GetSlot_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(OtterBrokerService_GetSlot_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validateOtterBrokerServiceRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kOtterBrokerService_Init_Name:
        if (message.expectsResponse())
          paramsClass = OtterBrokerService_Init_Params;
      break;
      case kOtterBrokerService_GetSlot_Name:
        if (message.expectsResponse())
          paramsClass = OtterBrokerService_GetSlot_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateOtterBrokerServiceResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kOtterBrokerService_Init_Name:
        if (message.isResponse())
          paramsClass = OtterBrokerService_Init_ResponseParams;
        break;
      case kOtterBrokerService_GetSlot_Name:
        if (message.isResponse())
          paramsClass = OtterBrokerService_GetSlot_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var OtterBrokerService = {
    name: 'blink.mojom.OtterBrokerService',
    kVersion: 0,
    ptrClass: OtterBrokerServicePtr,
    proxyClass: OtterBrokerServiceProxy,
    stubClass: OtterBrokerServiceStub,
    validateRequest: validateOtterBrokerServiceRequest,
    validateResponse: validateOtterBrokerServiceResponse,
  };
  OtterBrokerServiceStub.prototype.validator = validateOtterBrokerServiceRequest;
  OtterBrokerServiceProxy.prototype.validator = validateOtterBrokerServiceResponse;
  exports.OtterBrokerService = OtterBrokerService;
  exports.OtterBrokerServicePtr = OtterBrokerServicePtr;
  exports.OtterBrokerServiceAssociatedPtr = OtterBrokerServiceAssociatedPtr;
})();